- hosts: all
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Apache
    yum:
      name: httpd
      state: latest      

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started 

  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes 

  - name: Download Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/healet.zip
      dest: /var/www/html
    
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /var/www/html/healet.zip
      dest: /var/www/html
      remote_src: yes 

  - name: Move Template file to /var/www/html
    shell: "mv /tmp/healet-html/* /var/www/html/"
    args: 
      creates: /var/www/html/about.html